/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

interface nsIEditorGrammarCheckCallback;


[scriptable, uuid(8ac26150-586f-4b70-90df-07610b80b45f)]
interface nsIEditorGrammarCheck : nsISupports
{
    void poke(in string aValue);
	void registerAddon(in nsIEditorGrammarCheckCallback callback);
	void errorsFound(in unsigned long count, [array, size_is (count)] in unsigned long errors);
};

[scriptable, function, uuid(a234f68f-425c-4f48-ba8b-abf49621e24a)]
interface nsIEditorGrammarCheckCallback : nsISupports
{
  void doGrammarCheck(in string text);
};